jobs:
  include:
    - os: linux
      dist: xenial
      language: python
    - os: windows
      language: shell

python:
    - 2.7
    - 3.7
    - 3.8

install:
  - pip install future
  - python setup.py install
  - python setup.py install_ink --defaultext

script:
  - python test/runtests.py
  - python -m unittest test/runtests.py
