jobs:
  include:
    - os: linux
      dist: xenial
      language: python
      python: 2.7
    - os: linux
      dist: xenial
      language: python
      python: 3.7
    - os: windows
      language: shell
      before_install:
        - choco install python
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH


install:
  - pip install future
  - python setup.py install
  - python setup.py install_ink --defaultext

script:
  - python test/runtests.py
