jobs:
  include:
    - os: linux
      dist: xenial
      language: python
      python: 2.7
    - os: linux
      dist: xenial
      language: python
      python: 3.7
    - os: windows
      language: shell
      before_install:
        - choco install python
        - set PATH="%PATH%;C:\\Python38;C:\\Python38\\Scripts"


install:
  - pip install future
  - python setup.py install
  - python setup.py install_ink --defaultext

script:
  - python test/runtests.py
